// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkModelCode.Infrastructure.Data;

namespace NetworkModelCode.Infrastructure.Migrations
{
    [DbContext(typeof(NetworkModelContext))]
    partial class NetworkModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("NetworkModelCode.Core.Domain.Entities.ItemDataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CodeI")
                        .HasColumnType("int");

                    b.Property<int>("CodeJ")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ItemsDataSource");
                });

            modelBuilder.Entity("NetworkModelCode.Core.Domain.Entities.ItemTimeCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("EarlyFinish")
                        .HasColumnType("int");

                    b.Property<int>("EarlyStart")
                        .HasColumnType("int");

                    b.Property<int>("LateFinish")
                        .HasColumnType("int");

                    b.Property<int>("LateStart")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ReserveFreeTime")
                        .HasColumnType("int");

                    b.Property<int>("ReserveFullTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ItemsTimeCharacteristic");
                });

            modelBuilder.Entity("NetworkModelCode.Core.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NetworkModelCode.Core.Domain.Entities.ItemDataSource", b =>
                {
                    b.HasOne("NetworkModelCode.Core.Domain.Entities.Project", null)
                        .WithMany("ItemsDataSource")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetworkModelCode.Core.Domain.Entities.ItemTimeCharacteristic", b =>
                {
                    b.HasOne("NetworkModelCode.Core.Domain.Entities.Project", null)
                        .WithMany("ItemsTimeCharacteristic")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetworkModelCode.Core.Domain.Entities.Project", b =>
                {
                    b.Navigation("ItemsDataSource");

                    b.Navigation("ItemsTimeCharacteristic");
                });
#pragma warning restore 612, 618
        }
    }
}
